import type { CandidateItem, CurriculumModule, TutorTurn } from "@langtut/contracts";
import type { LearningActivity } from "@langtut/domain/browser";

export interface PromptPackageContext { manifest: { targetLanguage: { code: string; name: string }; sourceLanguage: { code: string; name: string } }; prompts: Record<string, string> }

export function scorePlacementAnswer(expected: string[], answer: string, locale?: string): boolean { const normalized = answer.normalize("NFC").toLocaleLowerCase(locale).replace(/[.!?]/g, "").trim(); return expected.some((value) => normalized.includes(value)); }
export function placementShouldComplete(value: { score: number; itemsAnswered: number; startedAt: string; maxItems: number }, itemCount: number, timestamp = Date.now()): boolean { const ratio = value.itemsAnswered ? value.score / value.itemsAnswered : 0; return (value.itemsAnswered >= 9 && ratio >= .78) || (value.itemsAnswered >= 6 && ratio <= .34) || (timestamp - Date.parse(value.startedAt)) / 60_000 >= 15 || value.itemsAnswered >= itemCount || value.itemsAnswered >= value.maxItems; }
export function recommendPlacement(score: number, answered: number, modules: CurriculumModule[]): string { const ratio = answered ? score / answered : 0; const position = ratio >= .75 ? .7 : ratio >= .65 ? .45 : ratio >= .55 ? .2 : 0; return modules[Math.min(modules.length - 1, Math.floor(modules.length * position))]?.id ?? modules[0]?.id ?? ""; }
export function rolesBeforeLearner(activity: LearningActivity): string[] { const index = activity.turnOrder.findIndex((id) => activity.roles.find((role) => role.id === id)?.controller === "learner"); return index < 0 ? [] : activity.turnOrder.slice(0, index); }
export function rolesAfterLearner(activity: LearningActivity): string[] { const index = activity.turnOrder.findIndex((id) => activity.roles.find((role) => role.id === id)?.controller === "learner"); const rotated = [...activity.turnOrder.slice(index + 1), ...activity.turnOrder.slice(0, index)]; const next = rotated.findIndex((id) => activity.roles.find((role) => role.id === id)?.controller === "learner"); return next < 0 ? rotated : rotated.slice(0, next); }
export function emptyTutorTurn(): TutorTurn { return { message: "", correction: "", explanation: "", newExample: "", errorTags: [], targetLanguageUse: "target", goalProgress: "partial", conversationState: "continue" }; }
export function normalizeTutorTurn(turn: TutorTurn, sourceLanguageName = "Deutsch"): TutorTurn { const plain = (value = "") => value.replace(/\*\*|__|`/g, "").replace(/\s+/g, " ").trim(); let message = plain(turn.message), explanation = plain(turn.explanation); const translated = message.match(new RegExp(`\\s*${escapeRegExp(sourceLanguageName)}:\\s*(.+)$`, "i")); if (translated?.index !== undefined) { message = message.slice(0, translated.index).trim(); explanation = [plain(translated[1]), explanation].filter(Boolean).join(" "); } return { message, correction: plain(turn.correction), explanation, newExample: plain(turn.newExample), errorTags: [...new Set((turn.errorTags ?? []).map(plain).filter(Boolean))].slice(0, 3), targetLanguageUse: turn.targetLanguageUse ?? "target", goalProgress: turn.goalProgress ?? "partial", conversationState: turn.conversationState ?? "continue" }; }

export function buildGenerationPrompt(pkg: PromptPackageContext, module: CurriculumModule, kind: CandidateItem["kind"], count: number, exclusions: string[], requestedIds?: string[]): string {
  const requested = new Set(requestedIds ?? []); const functions = requested.size ? module.functions.filter((id) => requested.has(id)) : module.functions; const milestones = requested.size ? module.grammarMilestones.filter(({ id }) => requested.has(id)) : module.grammarMilestones;
  const roleInstruction = kind === "vocab" ? `Erzeuge lexikalischen Wortschatz aus diesen Domänen: ${module.vocabDomains.join(", ")}. Erzeuge keine sprachwissenschaftlichen Bezeichnungen, keine einzelnen Buchstaben oder Zeichen und keine isolierten Flexionszellen. Verben stehen im Infinitiv, Nomen und Adjektive in der Wörterbuchform.` : kind === "chunk" ? `Erzeuge feste, direkt verwendbare Wendungen, die genau diese kommunikativen Funktionen realisieren: ${functions.join(", ")}.` : `Erzeuge je Grammatik-Milestone eine verständliche Regel-/Abrufnote: ${milestones.map((value) => `${value.id}: ${value.description}`).join(" | ")}.`;
  const taskId = kind === "vocab" ? "vocabulary_generation" : kind === "chunk" ? "chunk_generation" : "rule_generation";
  return `${renderPrompt(pkg.prompts[taskId], pkg)}\nErzeuge exakt ${count} ${kind}-Lernobjekte für ${pkg.manifest.targetLanguage.name} (Erklärungssprache ${pkg.manifest.sourceLanguage.name}).\nModulkennung: ${module.id}; Niveau: ${module.displayLevel}.\n${roleInstruction}\nVerwende ausschließlich diese fachlichen Tags: ${module.focusTags.join(", ")}.\nJedes Objekt enthält genau eine primäre Information, korrekte Orthografie und natürliche beidsprachige Beispiele.\nBereits verwendete oder abgelehnte Vorderseiten: ${JSON.stringify(exclusions)}.\nkind muss "${kind}" und moduleId muss "${module.id}" sein; itemId ist stabil und eindeutig. Für chunks ordne functionId zu; für rules milestoneId.`;
}
function renderPrompt(template: string, pkg: PromptPackageContext) { return template.replace(/\{\{([A-Za-z][A-Za-z0-9]*)\}\}/g, (_match, key: string) => ({ targetLanguage: pkg.manifest.targetLanguage.name, sourceLanguage: pkg.manifest.sourceLanguage.name, targetLanguageCode: pkg.manifest.targetLanguage.code, sourceLanguageCode: pkg.manifest.sourceLanguage.code } as Record<string, string>)[key] ?? ""); }
function escapeRegExp(value: string): string { return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
